# Generated by Django 3.1.4 on 2020-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='inactive_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('verif_key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
