# Generated by Django 3.1.4 on 2020-12-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_gallery',
            name='img_seen',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
