# Generated by Django 3.1.4 on 2020-12-11 05:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=50)),
                ('mock_url', models.TextField()),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
