# Generated by Django 3.1.4 on 2020-12-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
