# Generated by Django 3.1.4 on 2020-12-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0002_postingan_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
