# Generated by Django 3.1.4 on 2020-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0003_auto_20201211_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
