# Generated by Django 3.1.4 on 2020-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0004_auto_20201211_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='post_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
