# Generated by Django 3.1.4 on 2020-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0008_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='post_seen',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
