# Generated by Django 3.1.4 on 2020-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0009_postingan_post_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='pop_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
