# Generated by Django 3.1.4 on 2020-12-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0010_postingan_pop_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingan',
            name='pop_count',
        ),
    ]
