# Generated by Django 3.1.4 on 2020-12-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0012_auto_20201225_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='post_title',
            field=models.TextField(blank=True, default='Story', null=True),
        ),
    ]
