# Generated by Django 3.1.4 on 2020-12-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_more_info',
            name='verify',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
