# Generated by Django 3.1.4 on 2020-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_user_more_info_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_info',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
