# Generated by Django 3.1.4 on 2020-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20201211_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_more_info',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
