# Generated by Django 3.1.4 on 2020-12-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_user_more_info_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/img/avatar/')),
            ],
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='facebook',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='instagram',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='twitter',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
