# Generated by Django 3.1.4 on 2020-12-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20201213_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_info',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='instagram',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_more_info',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
    ]
