# Generated by Django 3.1.4 on 2020-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20201213_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('verified', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_more_info',
            name='verify',
        ),
    ]
