# Generated by Django 3.1.4 on 2020-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20201213_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_LinkTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
