# Generated by Django 3.1.4 on 2020-12-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_user_linktree_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
