# Generated by Django 3.1.4 on 2020-12-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_useravatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
