# Generated by Django 3.1.4 on 2020-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_delete_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_more_info',
            name='dribbble',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_more_info',
            name='github',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
    ]
