# Generated by Django 3.1.4 on 2020-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_auto_20201227_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('obj_type', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('obj_link', models.CharField(blank=True, default='#', max_length=300, null=True)),
                ('obj_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
