# Generated by Django 3.1.4 on 2020-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='act_type',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
